# Generated by Django 5.2.10 on 2026-02-25 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbag_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='punch',
            old_name='recorded_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='started_at',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punch',
            name='force',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='punch',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='sandbag_app.session'),
        ),
        migrations.AlterField(
            model_name='punch',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
