# Generated by Django 5.2.11 on 2026-03-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbag_app', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punch',
            name='volume',
        ),
        migrations.AddField(
            model_name='punch',
            name='location',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
